<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderManagement.Modules.Orders.Application\OrderManagement.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\OrderManagement.Modules.Orders.Domain\OrderManagement.Modules.Orders.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
